services:
  caddy:
    build: caddy
    user: nobody:nogroup
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data:rw
      - caddy_config:/config:rw
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./homepage/out:/srv/homepage:ro
      - $HOME/hidden:/srv/homepage/foo:ro
      - ./element/out:/srv/element:ro
      - $HOME/bags:/srv/bags:ro

  searxng:
    build: searxng
    user: nobody:nogroup
    cap_drop:
      - ALL
    environment:
      - SEARXNG_SECRET
    volumes:
      - ./searxng:/etc/searxng:ro

  # cache for searxng
  redis:
    image: redis:alpine
    user: nobody:nogroup
    cap_drop:
      - ALL
    command: redis-server --save "" --appendonly "no"
    tmpfs:
      - /var/lib/redis

  synapse:
    image: matrixdotorg/synapse:v1.85.2
    user: nobody:nogroup
    cap_drop:
      - ALL
    volumes:
      - synapse_data:/data:rw

  wbo:
    build: wbo
    user: nobody:nogroup
    cap_drop:
      - ALL
    volumes:
      - wbo_data:/opt/app/server-data:rw

  ntfy:
    build: ntfy
    user: nobody:nogroup
    cap_drop:
      - ALL
    command:
      - serve
    volumes:
      - ./ntfy/server.yml:/etc/ntfy/server.yml:ro
      - ntfy_data:/var/cache/ntfy:rw

  pigallery2:
    build: pigallery2
    user: nobody:nogroup
    cap_drop:
      - ALL
    environment:
      - NODE_ENV=production # set to 'debug' for full debug logging
    volumes:
      - pigallery2_db:/app/data/db:rw
      - pigallery2_tmp:/app/data/tmp:rw
      - ./pigallery2/config.json:/app/data/config/config.json:ro
      - $HOME/images:/app/data/images:ro

volumes:
  caddy_data:
  caddy_config:
  synapse_data:
  wbo_data:
  ntfy_data:
  pigallery2_db:
  pigallery2_tmp:
