#!/usr/bin/env bash

cd "$(realpath "$(dirname "${BASH_SOURCE[0]}")")" || exit 1

fmt="$(sed -z 's|\n| |g' << EOF
<a target="_blank" href="https://github.com/42LoCo42/homepage/commit/%H"><span class="bold blue">%h</span></a>
- <span class="bold green">(%ai)</span>
%s
- <span class="white">%an</span>
<span class="bold yellow">%d</span>
EOF
)"

getsize() {
	xbps-query -l \
	| awk '{sub(/-[^-]+_[^_]+$/, "", $2); print $2}' \
	| parallel xbps-query \
	| awk '/installed_size/ {sub(/K/, "k", $2); print $2}' \
	| paste -sd '+' \
	| qalc -t -s 'prec 2' \
	| awk 'NR == 3 {print $1 " " $2}'
}

case "$1" in
	logo) neofetch -L | aha -s -n > "caches/logo" ;;

	neofetch)
		USER=eleonora neofetch --backend off \
		| sed '
			s|Uptime.*|Uptime[m: UPTIME|;
			s|Memory.*|Memory[m: MEMORY|;
		' \
		| aha -s -n > "caches/neofetch"
	;;

	pkgs) cat << EOF > "caches/packages"
$(xbps-query -V | sed -E 's|: ([^ ]+)|: <span class="cyan">\1</span>|g')
<span class="blue">=======================================</span>
Total installed packages:        <span class="cyan">$(xbps-query -l | wc -l)</span>
Manually installed packages:     <span class="cyan">$(xbps-query -m | wc -l)</span>
Total size occupied by packages: <span class="cyan">$(getsize)</span>
<span class="blue">=======================================</span>
EOF
	;;

	git)
		git log --oneline --graph --format="$fmt" \
		| sed '
			s|Leon Schumacher|Eleonora|;
			s|&|&amp;|g;
		' > "caches/gitlog" ;;
esac
