#!/usr/bin/env bash

html_encode() {
	# adapted from https://stackoverflow.com/questions/12873682/short-way-to-escape-html-in-bash#12873723
	sed "
		s|&|\&amp;|g;
		s|<|\&lt;|g;
		s|>|\&gt;|g;
		s|\"|\&quot;|g;
		s|'|\&#39;|g
	"
}

urldecode() {
	: "${*//+/ }"
	echo -e "${_//%/\\x}"
}

list_thing() {
	printenv -0 | while IFS='=' read -rd $'\0' var _; do
		[[ "$var" =~ "$1"_.* ]] && echo "${var#"$1_"}"
	done
}

get_thing() { printenv "$1_$2"; }

list_headers() { list_thing HTTP             ; }
list_query()   { list_thing OPTION_QUERY     ; }
list_post()    { list_thing OPTION_POST      ; }
get_header()   { get_thing  HTTP "$1"        ; }
get_query()    { get_thing  OPTION_QUERY "$1"; }
get_post()     { get_thing  OPTION_POST "$1" ; }

basedir() { dirname "$(readlink -f "$0")"; }

form_decode() {
	oldifs="$IFS"
	IFS='&'
	for i in $1; do
		IFS='=' read -r key val <<< "$i"
		key="$(urldecode "$key")"
		val="$(urldecode "$val")"

		printf -v "OPTION_$2_$key" '%s' "$val"
		export "OPTION_$2_$key"
	done
	IFS="$oldifs"
}

query_decode() { form_decode "$QUERY_STRING" "QUERY"; }
post_decode()  { form_decode "$(cat)"        "POST" ; }
