#!/usr/bin/env bash

db() {
	hdb "$DOCUMENT_ROOT/../private/secure-users" "$@"
}

gen_hash() {
	printf '%s%s' "$1" "$2" | sha512sum | awk '{print $1}'
}

try_login() {
	entry="$(db get "$1/password")" || return 1
	salt="$(head -c32 <<< "$entry")"
	hash="$(tail -c+33 <<< "$entry")"
	cmp -s <(gen_hash "$salt" "$2") <<< "$hash"
}

register() {
	db set "$1" d || echo "User probably already exists"
	salt="$(base64 "/dev/urandom" | head -c 32)"
	read -rp "Enter password: " pass
	hash="$(gen_hash "$salt" "$pass")"
	echo "Setting hash for $1 = $salt -> $hash"
	db set "$1/password" f <<< "$salt$hash" || return 1
}

delete() {
	db del "$1"
}
